//Roles
export const ROLE_USER = 'User';
export const ROLE_ADMIN = 'Admin';
export const ROLE_GUEST = 'Guest';

//Token expiration
export const EXPIRES_IN = '10d';

//User signup method
export const SIGN_UP_PHONE = 'phone';

//swagger enum input
export const HOME = 'Home';
export const OFFICE = 'Office';
export const OTHERS = 'Others';

//payment
export const PENDING = 'Pending';
export const CurrencyCode = 'INR';
export const US_CURRENCY = 'usd';
export const Receipt = 'receipt1';
export const PAYMENT_SUCCESS = 'order.paid';
export const PAYMENT_FAILURE = 'payment.failed';
export const WEBHOOK_SUCCESS = 'Success';
export const WEBHOOK_FAILURE = 'Failure';
export const STRIPE_PAYMENT_SUCCESS = 'payment_intent.succeeded';
export const STRIPE_PAYMENT_FAILED = 'payment_intent.payment_failed';

//orders
export const DONATION = 'Donation';
export const ONLINE_ORDER = 'Online';
export const OFFLINE_ORDER = 'OfflineOrder';
// order screen name
export const ORDER_REPORTS = 'Reports';
//vastram type
export const CREATED_VASTRAMS = 'createdVastrams';
export const BOOKED_VASTRAMS = 'bookedVastrams';

//DB query config
export const NOTIFICATION_ADMIN_SKIP = 50;
export const NOTIFICATION_NON_ADMIN_SKIP = 10;

//order notification
export const ORDER = 'Order';
export const NEW_ORDER = 'Order';

//notification
export const NOTIFICATIONS = 'Notifications';
export const NEW_NOTIFICATION = 'NewNotification';

//service calendar event notification
export const EVENT = 'Event';
export const NEW_EVENT = 'NewEvent';
export const AMAVASYA = 'AMAVASYA';

// file upload url path
export const CD = '..';
export const FOLDER_PUBLIC = 'public';

//News Letter
export const NEWS_LETTER = 'newsLetter';

//donation
export const DONATION_SERVICE = 'Donation_Service';

//
export const VASTRAM = 'Vastram';
export const GENERIC = 'Generic';
export const REQURING = 'Requring';

//deity
export const DEITY = 'deity';

//occurence
export const DAILY = 'DAILY';
export const WEEKLY = 'WEEKLY';
export const MONTHLY_DAYS = 'MONTHLY_DAYS';
export const MONTHLY_DATES = 'MONTHLY_DATES';
export const CUSTOM_DATES_PICKER = 'CUSTOM_DATES_PICKER';
export const DATES_RANGE = 'DATES_RANGE';
export const EVERY_MONDAY = 'EVERY_MONDAY';
export const EVERY_TUESDAY = 'EVERY_TUESDAY';
export const EVERY_WEDNESDAY = 'EVERY_WEDNESDAY';
export const EVERY_THURSDAY = 'EVERY_THURSDAY';
export const EVERY_FRIDAY = 'EVERY_FRIDAY';
export const EVERY_SATURDAY = 'EVERY_SATURDAY';
export const EVERY_SUNDAY = 'EVERY_SUNDAY';
export const MONTHLY_1ST_SUNDAY = 'MONTHLY_1ST_SUNDAY';
export const MONTHLY_2ND_SUNDAY = 'MONTHLY_2ND_SUNDAY';
export const MONTHLY_3RD_SUNDAY = 'MONTHLY_3RD_SUNDAY';
export const MONTHLY_4TH_SUNDAY = 'MONTHLY_4TH_SUNDAY';
export const MONTHLY_5TH_SUNDAY = 'MONTHLY_5TH_SUNDAY';
export const MONTHLY_1ST_MONDAY = 'MONTHLY_1ST_MONDAY';
export const MONTHLY_2ND_MONDAY = 'MONTHLY_2ND_MONDAY';
export const MONTHLY_3RD_MONDAY = 'MONTHLY_3RD_MONDAY';
export const MONTHLY_4TH_MONDAY = 'MONTHLY_4TH_MONDAY';
export const MONTHLY_5TH_MONDAY = 'MONTHLY_5TH_MONDAY';
export const MONTHLY_1ST_TUESDAY = 'MONTHLY_1ST_TUESDAY';
export const MONTHLY_2ND_TUESDAY = 'MONTHLY_2ND_TUESDAY';
export const MONTHLY_3RD_TUESDAY = 'MONTHLY_3RD_TUESDAY';
export const MONTHLY_4TH_TUESDAY = 'MONTHLY_4TH_TUESDAY';
export const MONTHLY_5TH_TUESDAY = 'MONTHLY_5TH_TUESDAY';
export const MONTHLY_1ST_WEDNESDAY = 'MONTHLY_1ST_WEDNESDAY';
export const MONTHLY_2ND_WEDNESDAY = 'MONTHLY_2ND_WEDNESDAY';
export const MONTHLY_3RD_WEDNESDAY = 'MONTHLY_3RD_WEDNESDAY';
export const MONTHLY_4TH_WEDNESDAY = 'MONTHLY_4TH_WEDNESDAY';
export const MONTHLY_5TH_WEDNESDAY = 'MONTHLY_5TH_WEDNESDAY';
export const MONTHLY_1ST_THURSDAY = 'MONTHLY_1ST_THURSDAY';
export const MONTHLY_2ND_THURSDAY = 'MONTHLY_2ND_THURSDAY';
export const MONTHLY_3RD_THURSDAY = 'MONTHLY_3RD_THURSDAY';
export const MONTHLY_4TH_THURSDAY = 'MONTHLY_4TH_THURSDAY';
export const MONTHLY_5TH_THURSDAY = 'MONTHLY_5TH_THURSDAY';
export const MONTHLY_1ST_FRIDAY = 'MONTHLY_1ST_FRIDAY';
export const MONTHLY_2ND_FRIDAY = 'MONTHLY_2ND_FRIDAY';
export const MONTHLY_3RD_FRIDAY = 'MONTHLY_3RD_FRIDAY';
export const MONTHLY_4TH_FRIDAY = 'MONTHLY_4TH_FRIDAY';
export const MONTHLY_5TH_FRIDAY = 'MONTHLY_5TH_FRIDAY';
export const MONTHLY_1ST_SATURDAY = 'MONTHLY_1ST_SATURDAY';
export const MONTHLY_2ND_SATURDAY = 'MONTHLY_2ND_SATURDAY';
export const MONTHLY_3RD_SATURDAY = 'MONTHLY_3RD_SATURDAY';
export const MONTHLY_4TH_SATURDAY = 'MONTHLY_4TH_SATURDAY';
export const MONTHLY_5TH_SATURDAY = 'MONTHLY_5TH_SATURDAY';
export const MONTHLY_DATES_1 = 'MONTHLY_DATES_1';
export const MONTHLY_DATES_2 = 'MONTHLY_DATES_2';
export const MONTHLY_DATES_3 = 'MONTHLY_DATES_3';
export const MONTHLY_DATES_4 = 'MONTHLY_DATES_4';
export const MONTHLY_DATES_5 = 'MONTHLY_DATES_5';
export const MONTHLY_DATES_6 = 'MONTHLY_DATES_6';
export const MONTHLY_DATES_7 = 'MONTHLY_DATES_7';
export const MONTHLY_DATES_8 = 'MONTHLY_DATES_8';
export const MONTHLY_DATES_9 = 'MONTHLY_DATES_9';
export const MONTHLY_DATES_10 = 'MONTHLY_DATES_10';
export const MONTHLY_DATES_11 = 'MONTHLY_DATES_11';
export const MONTHLY_DATES_12 = 'MONTHLY_DATES_12';
export const MONTHLY_DATES_13 = 'MONTHLY_DATES_13';
export const MONTHLY_DATES_14 = 'MONTHLY_DATES_14';
export const MONTHLY_DATES_15 = 'MONTHLY_DATES_15';
export const MONTHLY_DATES_16 = 'MONTHLY_DATES_16';
export const MONTHLY_DATES_17 = 'MONTHLY_DATES_17';
export const MONTHLY_DATES_18 = 'MONTHLY_DATES_18';
export const MONTHLY_DATES_19 = 'MONTHLY_DATES_19';
export const MONTHLY_DATES_20 = 'MONTHLY_DATES_20';
export const MONTHLY_DATES_21 = 'MONTHLY_DATES_21';
export const MONTHLY_DATES_22 = 'MONTHLY_DATES_22';
export const MONTHLY_DATES_23 = 'MONTHLY_DATES_23';
export const MONTHLY_DATES_24 = 'MONTHLY_DATES_24';
export const MONTHLY_DATES_25 = 'MONTHLY_DATES_25';
export const MONTHLY_DATES_26 = 'MONTHLY_DATES_26';
export const MONTHLY_DATES_27 = 'MONTHLY_DATES_27';
export const MONTHLY_DATES_28 = 'MONTHLY_DATES_28';
export const MONTHLY_DATES_29 = 'MONTHLY_DATES_29';
export const MONTHLY_DATES_30 = 'MONTHLY_DATES_30';
export const MONTHLY_DATES_31 = 'MONTHLY_DATES_31';
export const WEEKLY_OCCURENCE = {
  EVERY_MONDAY,
  EVERY_TUESDAY,
  EVERY_WEDNESDAY,
  EVERY_THURSDAY,
  EVERY_FRIDAY,
  EVERY_SATURDAY,
  EVERY_SUNDAY,
};
export const MONTHLY_DAYS_OCCURENCE = {
  MONTHLY_1ST_SUNDAY,
  MONTHLY_2ND_SUNDAY,
  MONTHLY_3RD_SUNDAY,
  MONTHLY_4TH_SUNDAY,
  MONTHLY_5TH_SUNDAY,
  MONTHLY_1ST_MONDAY,
  MONTHLY_2ND_MONDAY,
  MONTHLY_3RD_MONDAY,
  MONTHLY_4TH_MONDAY,
  MONTHLY_5TH_MONDAY,
  MONTHLY_1ST_TUESDAY,
  MONTHLY_2ND_TUESDAY,
  MONTHLY_3RD_TUESDAY,
  MONTHLY_4TH_TUESDAY,
  MONTHLY_5TH_TUESDAY,
  MONTHLY_1ST_WEDNESDAY,
  MONTHLY_2ND_WEDNESDAY,
  MONTHLY_3RD_WEDNESDAY,
  MONTHLY_4TH_WEDNESDAY,
  MONTHLY_5TH_WEDNESDAY,
  MONTHLY_1ST_THURSDAY,
  MONTHLY_2ND_THURSDAY,
  MONTHLY_3RD_THURSDAY,
  MONTHLY_4TH_THURSDAY,
  MONTHLY_5TH_THURSDAY,
  MONTHLY_1ST_FRIDAY,
  MONTHLY_2ND_FRIDAY,
  MONTHLY_3RD_FRIDAY,
  MONTHLY_4TH_FRIDAY,
  MONTHLY_5TH_FRIDAY,
  MONTHLY_1ST_SATURDAY,
  MONTHLY_2ND_SATURDAY,
  MONTHLY_3RD_SATURDAY,
  MONTHLY_4TH_SATURDAY,
  MONTHLY_5TH_SATURDAY,
};
export const MONTHLY_DATES_OCCURENCE = {
  MONTHLY_DATES_1,
  MONTHLY_DATES_2,
  MONTHLY_DATES_3,
  MONTHLY_DATES_4,
  MONTHLY_DATES_5,
  MONTHLY_DATES_6,
  MONTHLY_DATES_7,
  MONTHLY_DATES_8,
  MONTHLY_DATES_9,
  MONTHLY_DATES_10,
  MONTHLY_DATES_11,
  MONTHLY_DATES_12,
  MONTHLY_DATES_13,
  MONTHLY_DATES_14,
  MONTHLY_DATES_15,
  MONTHLY_DATES_16,
  MONTHLY_DATES_17,
  MONTHLY_DATES_18,
  MONTHLY_DATES_19,
  MONTHLY_DATES_20,
  MONTHLY_DATES_21,
  MONTHLY_DATES_22,
  MONTHLY_DATES_23,
  MONTHLY_DATES_24,
  MONTHLY_DATES_25,
  MONTHLY_DATES_26,
  MONTHLY_DATES_27,
  MONTHLY_DATES_28,
  MONTHLY_DATES_29,
  MONTHLY_DATES_30,
  MONTHLY_DATES_31,
};
export const OCCURENCE_CONST = [
  DAILY,
  EVERY_SUNDAY,
  EVERY_MONDAY,
  EVERY_TUESDAY,
  EVERY_WEDNESDAY,
  EVERY_THURSDAY,
  EVERY_FRIDAY,
  EVERY_SATURDAY,
  MONTHLY_1ST_SUNDAY,
  MONTHLY_2ND_SUNDAY,
  MONTHLY_3RD_SUNDAY,
  MONTHLY_4TH_SUNDAY,
  MONTHLY_5TH_SUNDAY,
  MONTHLY_1ST_MONDAY,
  MONTHLY_2ND_MONDAY,
  MONTHLY_3RD_MONDAY,
  MONTHLY_4TH_MONDAY,
  MONTHLY_5TH_MONDAY,
  MONTHLY_1ST_TUESDAY,
  MONTHLY_2ND_TUESDAY,
  MONTHLY_3RD_TUESDAY,
  MONTHLY_4TH_TUESDAY,
  MONTHLY_5TH_TUESDAY,
  MONTHLY_1ST_WEDNESDAY,
  MONTHLY_2ND_WEDNESDAY,
  MONTHLY_3RD_WEDNESDAY,
  MONTHLY_4TH_WEDNESDAY,
  MONTHLY_5TH_WEDNESDAY,
  MONTHLY_1ST_THURSDAY,
  MONTHLY_2ND_THURSDAY,
  MONTHLY_3RD_THURSDAY,
  MONTHLY_4TH_THURSDAY,
  MONTHLY_5TH_THURSDAY,
  MONTHLY_1ST_FRIDAY,
  MONTHLY_2ND_FRIDAY,
  MONTHLY_3RD_FRIDAY,
  MONTHLY_4TH_FRIDAY,
  MONTHLY_5TH_FRIDAY,
  MONTHLY_1ST_SATURDAY,
  MONTHLY_2ND_SATURDAY,
  MONTHLY_3RD_SATURDAY,
  MONTHLY_4TH_SATURDAY,
  MONTHLY_5TH_SATURDAY,
  MONTHLY_DATES_1,
  MONTHLY_DATES_2,
  MONTHLY_DATES_3,
  MONTHLY_DATES_4,
  MONTHLY_DATES_5,
  MONTHLY_DATES_6,
  MONTHLY_DATES_7,
  MONTHLY_DATES_8,
  MONTHLY_DATES_9,
  MONTHLY_DATES_10,
  MONTHLY_DATES_11,
  MONTHLY_DATES_12,
  MONTHLY_DATES_13,
  MONTHLY_DATES_14,
  MONTHLY_DATES_15,
  MONTHLY_DATES_16,
  MONTHLY_DATES_17,
  MONTHLY_DATES_18,
  MONTHLY_DATES_19,
  MONTHLY_DATES_20,
  MONTHLY_DATES_21,
  MONTHLY_DATES_22,
  MONTHLY_DATES_23,
  MONTHLY_DATES_24,
  MONTHLY_DATES_25,
  MONTHLY_DATES_26,
  MONTHLY_DATES_27,
  MONTHLY_DATES_28,
  MONTHLY_DATES_29,
  MONTHLY_DATES_30,
  MONTHLY_DATES_31,
];

//donation service
export const FIXED = 'Fixed';
export const VARIABLE = 'Variable';

export const CC_AVENUE = {
  STATUS: {
    SUCCESS: 'Success',
    FAILURE: 'Failure',
    ABORTED: 'Aborted',
    INVALID: 'Invalid',
  },
  CURRENCY: 'INR',
  LANGUAGE: 'en',
};

export const CART = 'Cart';

export const TEMPLE_ID = 'Temple-1';
export const SIGNUP_METHOD_PHONE = 'phone';
export const SIGNUP_METHOD_EMAIL = 'google';
export const KB_500 = 512000;
export const NEW_TEMPLE_ID = 'folsom-Temple';
